name: TEST_Workflow_dispatch

on:
  workflow_dispatch:
     inputs: 
        param1:
          description: 'param1 identifier'
          required: true
        param2:
          description: 'param2 identifier'
          required: true
jobs:

  build:
    runs-on: ubuntu-latest
    steps:
      - name : Step-1
        run: echo "hello from step 1"
        
      - name: Sleep for 30 seconds
        run: sleep 30s
        shell: bash
      - uses: actions/checkout@v3

      - name: Run a one-line script
        run: echo "Hello, world!"

